name: 'Debugging with ttyd'
description: 'Debug your GitHub Actions Environment interactively through web browser'
author: 'Fawaz Ahmed'

# Define your inputs here.
inputs:
  credentials:
    description: 'Set credentials in username:password format to access the terminal. Default is passwordless terminal access'
    required: false

runs:
  using: node20
  main: dist/index.js
