name: 'Debugging with ttyd'
description: 'Debug your GitHub Actions Environment interactively through web browser'
author: 'Fawaz Ahmed'

# Define your inputs here.
inputs:
  credentials:
    description: 'Set credentials in username:password format to access the terminal. Default is passwordless terminal access'
    required: false

runs:
  using: "composite"
  steps:

    - name: Set credentials if exists
      shell: bash
      run: |
        echo ${{ github.event.inputs.credentials }}
        if [ ! -z ${{ github.event.inputs.credentials }} ]; then export credentials="-c $credentials"; fi

    - name: Install dependencies and run command in windows
      if: ${{ contains(runner.os, 'windows') }}
      shell: bash
      run: |
        wget -O ../ttyd.exe https://github.com/tsl0922/ttyd/releases/download/1.7.3/ttyd.win32.exe
        wget -O ../cloudflared.exe https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
        ../ttyd.exe -p 8391 $credentials -a -W bash &
        ../cloudflared.exe tunnel --url http://localhost:8391 > ../mylog.txt 2>&1 &

    - name: Install dependencies and run command in linux
      if: ${{ contains(runner.os, 'linux') }}
      shell: bash
      run: |
        echo $credentials
        wget -O ../ttyd https://github.com/tsl0922/ttyd/releases/download/1.7.4/ttyd.x86_64
        wget -O ../cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        chmod 777 ../ttyd
        chmod 777 ../cloudflared
        ../ttyd -p 8391 $credentials -a -W bash &
        ../cloudflared tunnel --url http://localhost:8391 > ../mylog.txt 2>&1 &

    - name: Install dependencies and run command in macOS
      if: ${{ contains(runner.os, 'macos') }}
      shell: bash
      run: |
        brew install ttyd cloudflare/cloudflare/cloudflared
        ttyd -p 8391 $credentials -a -W bash
        cloudflared tunnel --url http://localhost:8391 > ../mylog.txt 2>&1 &

    - name: check for continue file
      shell: bash
      run: |
        while [ ! -f ./continue ]; do sleep 5; cat ../mylog.txt; echo $credentials; done